# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "9405a40a4f33cb90910430d47ab1db1e5185b0a2"

[[deps.PackageDataCleaning]]
path = "."
uuid = "3a50491a-824b-4118-a264-eb0a3c113a9e"
version = "1.0.0-DEV"
